config/routes.rb
Rails.application.routes.draw do
  resources :potential_buyers
  resources :queries
  resources :properties
  resources :companies
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  # Custom Routes for Users
  match '/user/new', to: 'users#new', via: 'get'
  match '/user/switch', to: 'users#switch', via: 'get', as: 'switch_role_user'
  match '/user/create', to: 'users#create', via: 'post'
  match '/user/:id/edit', to: 'users#edit', via: 'get', as: 'user_edit'
  match '/user/:id', to: 'users#update', via: 'put'
  match '/user/:id', to: 'users#update', via: 'patch'
  match '/user/:id', to: 'users#destroy', via: 'delete'
  match '/users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  # Routes for Property Search
  match '/property/search' => 'properties#search', :via => 'post', :as=> 'property_search'
  # Route to send Enquiry
  match '/property/enquiry' => 'queries#create', :via => 'post', :as => 'new_enquiry'

  # Route to Create New Reply
  match '/queries/reply' => 'queries#reply', :via => :post, :as => :new_reply

  match '/users', to: 'users#index', via: 'get'
  match '/hunters', to: 'users#hunter', via: 'get'
  match '/realtors', to: 'users#realtor', via: 'get'
  root to: "real_estate_app#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_one :company
  has_many :queries, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:google]

  validates_presence_of :email, :first_name
  enum contact_method: [:email, :text, :call]

  def self.from_omniauth(auth)
    user = User.where(:provider => auth.provider, :uid => auth.uid ).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create!(
          provider: auth.provider,
          email: auth.info.email,
          first_name: auth.info.email.split('@')[0],
          uid: auth.uid,
          is_hunter: 1,
          is_realtor: 0,
          password: Devise.friendly_token[0,20],
        )
      end
    end
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :validate_user, only: [:show, :update, :destroy, :index, :new], :if => lambda{ Rails.env.test?}
  before_action :authenticate_user!

  # GET /
  def index
    if user_signed_in? && !current_user.is_admin
      respond_to do |format|
        format.html { redirect_to root_path }
      end
    end
    @users = User.all 
  end

  # GET /hunters
  def hunter 
    if user_signed_in? && !current_user.is_admin
      respond_to do |format|
        format.html { redirect_to root_path }
      end
    end
    @users = User.where(is_hunter: 1)
  end

  # GET /realtor
  def realtor 
    if user_signed_in? && !current_user.is_admin
      respond_to do |format|
        format.html { redirect_to root_path }
      end
    end
    @users= User.where(is_realtor: 1)
  end

  def switch
    if session[:role].present? 
      if session[:role] == 'hunter'
        session[:role] = 'realtor'
      elsif session[:role] == 'realtor'
        session[:role] = 'hunter'
      end
    else
      if current_user.is_realtor
        session[:role] = 'realtor'
      else
        session[:role] = 'hunter'
      end
    end
    redirect_to root_path
  end

  # Not implemented yet.
  def show
  end

  # GET /user/id/edit
  def edit
  end


  def validate_user
    if !user_signed_in?
      redirect_to root_path
    end

    if @user != @current_user
      redirect_to root_path
    end
  end



  # GET /user/new
  def new
    if user_signed_in? && !current_user.is_admin
      respond_to do |format|
        format.html { redirect_to root_path }
      end
    end
    @user = User.new
  end

  # PATCH/PUT /user/1
  # PATCH/PUT /user/1.json
  def update
    respond_to do |format|
      if @user.update_without_password(user_params)
        format.html { redirect_to root_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # Create User Account
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save!
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # Destroy user Account
  def destroy
    @user = User.find(params[:id])
    # Property.where(@property.user_id == params[:id]).destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'User was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.fetch(:user, {})
    params.require(:user).permit(:first_name, :last_name, :phone, :email, :password, :password_confirmation, :is_hunter, :is_realtor, :company_id, :contact_method, :current_role)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>

  <div class="card" style="margin-top:25px">
    <div class="card-header"> 
      <h4> Don't have an account? <h4>
    </div>
    <div class="card-body">
      <%= link_to "Sign up", new_registration_path(resource_name), :class=> "btn btn-secondary"%>
    </div>
  </div>

<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_table.html.erb
<table class="table">
  <thead>
  <tr>
    <th> Name </th>
    <th> Email </th>
    <th> Phone </th>
    <th> Contact </th>
    <th> Company </th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| if !user.is_admin %>
    <tr>
      <td> <%= user.first_name  %></td>
      <td> <%= user.email %></td>
      <td> <%= user.phone %></td>
      <td> 
        <% if user.contact_method == 'text'%>
          <%= "Text on #{user.phone}" %>
        <% elsif user.contact_method == 'phone' %>
          <%= "Call on #{user.phone}" %>
        <% else %>
          <%= "Mail on #{user.email}" %>
        <% end %>
      </td>
      <td> 
        <% if user.is_realtor && user.company_id %>
          <%= Company.find(user.company_id).name %> 
        <% end %>
      </td>
      <td><%= link_to 'Edit', {:controller => :users, :action => :edit, :id => user.id } %></td>
      <td> <%= link_to 'Destroy', admin_destroy_user_path(user), method: :delete, data: { confirm: "You sure?" } %></td>
    </tr>
  <% end %>
  <% end %>
  </tbody>
</table>