config/routes.rb
Rails.application.routes.draw do
  resources :potential_buyers
  resources :queries
  resources :properties
  resources :companies
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  # Custom Routes for Users
  match '/user/new', to: 'users#new', via: 'get'
  match '/user/switch', to: 'users#switch', via: 'get', as: 'switch_role_user'
  match '/user/create', to: 'users#create', via: 'post'
  match '/user/:id/edit', to: 'users#edit', via: 'get', as: 'user_edit'
  match '/user/:id', to: 'users#update', via: 'put'
  match '/user/:id', to: 'users#update', via: 'patch'
  match '/user/:id', to: 'users#destroy', via: 'delete'
  match '/users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  # Routes for Property Search
  match '/property/search' => 'properties#search', :via => 'post', :as=> 'property_search'
  # Route to send Enquiry
  match '/property/enquiry' => 'queries#create', :via => 'post', :as => 'new_enquiry'

  # Route to Create New Reply
  match '/queries/reply' => 'queries#reply', :via => :post, :as => :new_reply

  match '/users', to: 'users#index', via: 'get'
  match '/hunters', to: 'users#hunter', via: 'get'
  match '/realtors', to: 'users#realtor', via: 'get'
  root to: "real_estate_app#index"
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :company
  validates_presence_of :address, :owner, :price, :size
  enum basement: [:No, :Yes]
  enum style: [:townhouse, :apartment]
  enum floors: [:"1", :"2", :"3", :"4", :"5+"]
  # has_many_attached :images
  mount_uploader :image, ImageUploader
  serialize :image, JSON
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, only:[:search, :new_search]


  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    if current_user.company_id == nil
      redirect_to user_edit_path(current_user.id), :flash => { :error => "Cannot List a new Property without a Company" }
      return
    end
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)
    # @property.images.attach(params[:images])
    @property.company_id = current_user.company_id
    @property.created_by = current_user.id
    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  INTEGER_MAX = 2147483647
  SIZE_MAPPING = {
    1 => [0, 500],
    2 => [500, 1500],
    3 => [1500, 3000],
    4 => [3000, INTEGER_MAX]
  }
  PRICE_MAPPING = {
    1 => [0, 100000],
    2 => [100000, 250000],
    3 => [250000, 500000],
    4 => [500000, 1000000],
    5 => [1000000, INTEGER_MAX]
  }

  def search 
    @sp = params.fetch(:search_params, {})
    @properties = Property.all
    @properties = @properties.where(:size => SIZE_MAPPING[@sp['size'].to_i][0]...SIZE_MAPPING[@sp['size'].to_i][1]) if @sp['size'].present?
    @properties = @properties.where(['address LIKE ?', "%#{@sp['address']}%"]) if @sp['address'].present? && @sp['address'] != ""
    @properties = @properties.where(:price => PRICE_MAPPING[@sp['price'].to_i][0]...PRICE_MAPPING[@sp['price'].to_i][1]) if @sp['price'].present?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_property
    @property = Property.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def property_params
    params.fetch(:property, {})
    params.require(:property).permit(:owner, :address, :price, :size, :floors, :style, :title, :basement, :content, :image)
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
  def size_options
    [["0-500", 1], ["500-1500", 2], ["1500-3000", 3], ["3000+", 4]]
  end
  def price_options
    [["0-100 Thousand", 1], ["100-250 Thousand", 2], ["250-500 Thousand", 3], ["500 Thousand - 1 Million", 4], ["1 Million +", 5]]
  end
end

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true, :html => {multipart: true}) do |form| %>

  <div class="form-group">
    <%= form.label 'Address' %><br />
    <%= form.text_field :address, autofocus: true, autocomplete: "name", :class=> "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label 'Owner' %><br />
    <%= form.text_field :owner, autofocus: true, autocomplete: "name", :class=> "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label 'Price' %><br />
    <%= form.text_field :price, autofocus: true, autocomplete: "name", :class=> "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label 'Size' %><br />
    <%= form.text_field :size, autofocus: true, autocomplete: "name", :class=> "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label 'Basement' %><br />
    <%= form.select(:basement, Property.basements.keys, {}, { :class=> "form-control" })%>
  </div>

  <div class="form-group">
    <%= form.label 'Floors' %><br />
    <%= form.select(:floors, Property.floors.keys, {}, { :class=> "form-control" })%>
  </div>

  <div class="form-group">
    <%= form.label 'Style' %><br />
    <%= form.select(:style, Property.styles.keys, {}, {:class=> "form-control"})%>
  </div>
  <div class="form-group">
    <%= form.file_field :image %>
  </div>

  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# form-control-file %>
  <div class="form-group">
    <%= form.submit :class=> "btn btn-success" %>
    <%= link_to 'Back', properties_path, :class => "btn btn-secondary float-right" %>
  </div>
<% end %>

app/views/properties/_queryform.html.erb
<%= form_for :query_params, url: new_enquiry_path do |f| %>
<div class="container" , style="margin-top:50px; margin-bottom:50px;">
  <h2>Send an Enquiry</h2>
  <div class="form-group">
    <%= f.label 'Subject' %><br />
    <%= f.text_field :subject, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label 'Subject' %><br />
    <%= f.text_area :message, :class => "form-control" %>
  </div>

  <%# Adding Current Property ID as a hidden field in the form %>
  <%= f.hidden_field :property_id, :value => @property.id %>
  
  <div class="form-group">
      <%= f.submit "Send", :class=>"btn btn-success float-right" %>
  </div>
</div>
<% end %>

app/views/properties/_searchform.html.erb
<%= form_for :search_params, url: property_search_path do |f| %>
<div class="container" , style="margin-top:50px; margin-bottom:50px;">
  <h2>Search</h2>
  <div class="form-row">
    <div class="form-group col-md-4">
      <%= f.label 'Address' %><br />
      <%= f.text_field :address, autofocus: true, :class=>"form-control" %>
    </div>

    <div class="form-group col-md-4">
      <%= f.label 'Property Size' %><br />
      <%= f.select(:size, size_options, { :include_blank => true }, { :class => "form-control" }) %>
    </div>

    <div class="form-group col-md-4">
      <%= f.label 'Property Price' %><br />
      <%= f.select(:price, price_options, { :include_blank => true }, { :class => "form-control" }) %>
    </div>
    
  </div>
  <div class="form-group">
      <%= f.submit "Search", :class=>"btn btn-success float-right" %>
  </div>
</div>
<% end %>

app/views/properties/_table.html.erb
<table class="table">
  <thead>
    <tr>
      <%# <th>Pic</th> %>
      <th>Price</th>
      <th>Address</th>
      <th>Size</th>
      <th>Floors</th>
      <th>Contact</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <%# <td><%= property.image </td> %>
        <td><%= property.price %></td>
        <td><%= property.address %></td>
        <td><%= property.size %></td>
        <td><%= property.floors %></td>
        <td>
          <% if (property.company_id)%>
            <%= Company.find(property.company_id).name %>
          <% end %>
        </td>

        <td><%= link_to 'Show', property %></td>
        <% if current_user.is_admin || ( current_user.is_realtor && session[:role] == 'realtor' && current_user.company_id == property.company_id ) %>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
          <%end %>
          <% if current_user.is_admin || ( current_user.is_realtor && session[:role] == 'realtor' && current_user.company_id == property.company_id ) %>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/properties/edit.html.erb
<%= render "partials/navbar" %>
<div class="container">
  <div class="card" style="width: 60rem; margin-top: 50px;" >
    <div class="card-header">
      <h1>Edit Property</h1>
      </div>
    <div class="card-body">
      <%= render 'form', property: @property %>
    </div>
  </div>
  </div>
</div>

app/views/properties/index.html.erb
<%= render "partials/navbar" %>
<p id="notice"><%= notice %></p>
<%= render 'searchform' %>

<div class="container">
  <h1>Properties</h1>
  <%= render 'table' %>
  <% if current_user.is_admin || current_user.is_realtor %>
    <%= link_to 'New Property', new_property_url, :class=>'btn-lg btn-success' %>
  <% end %>
</div>

app/views/properties/new.html.erb
<%= render "partials/navbar" %>

<div class="container">
  <div class="card" style="width: 36rem; margin-top: 50px;" >
    <div class="card-header">
      <h1>New Property</h1>
      </div>
    <div class="card-body">
      <%= render 'form', property: @property %>
    </div>
  </div>
  </div>
</div>

app/views/properties/search.html.erb
<%= render "partials/navbar" %>
<%= render 'searchform' %>
<div class="container">
  <h1>Matching Properties</h1>
  <%= render 'table' %>

  <% if current_user.is_admin || ( current_user.is_realtor && current_user.company_id == property.user_id ) %>
  <%= link_to 'New Property', new_property_path %>
  <%end %>
</div>

app/views/properties/show.html.erb
<%= render "partials/navbar" %>

<div class="container" style="margin-top:50px">
  <div class="card">
    <% if @property.image_url %>
      <%= image_tag @property.image_url, :class=>"card-img-top", :style=>"width:300px" %>
    <% end %>
    <div class="card-body">
      <h5 class="card-title">
        <%= @property.address %>
      </h5>
      <p>
        <strong>Address :</strong>
        <%= @property.address %>
      </p>


      <p> <strong>Owner : </strong>
        <%= @property.owner %>
      </p>

      <p>
        <strong>Price :</strong>
        <%= @property.price.to_s %>
      </p>

      <p>
        <strong>Size :</strong>
        <%= @property.size.to_s %>
      </p>

      <p>
        <strong>Floors :</strong>
        <%= @property.floors.to_s %>
      </p>

      <p>
        <strong>Basement :</strong>
        <%= @property.basement.to_s %>
      </p>


      <p>
        <strong>Style :</strong>
        <%= @property.style %>
      </p>

      <p>
        <strong>Company :</strong>
        <% if @property.company_id != nil %>
          <%= Company.find(@property.company_id).name %>
        <% end %>
      </p>

      <% if current_user.is_admin || ( current_user.is_realtor && current_user.company_id == @property.company_id ) %>
        <%= form_with(model: @property, local: true, :html => {multipart: true}) do |form| %>
          <div class="form-group">
            <%= form.file_field :image %>
          </div>
          <div class="form-group">
            <%= form.submit :class=> "btn btn-success" %>
          </div>
        <% end %>
      <% end %>
      <% if current_user.is_admin || ( current_user.is_hunter ) %>
      <%= link_to 'Interested', potential_buyers_path(property_id: @property.id), :method => 'post', :class=>"btn btn-success" %>
       <% end %>

      <% if current_user.is_realtor && session[:role] == 'realtor' && current_user.company_id == @property.company_id %>
        <%= link_to 'List of Potential Buyers', potential_buyers_path(property_id: @property.id), :method => 'get', :class=>"btn btn-success" %>
      <% end %>

      <%= link_to 'Back', properties_path, :class=>"btn btn-secondary" %>

    </div>
  </div>
</div>

<%# Show only to users who have not sent the query yet %>
<% if (current_user.is_hunter && Query.where(property_id: @property.id, user_id: current_user.id).empty?) || current_user.is_admin %>
  <%= render 'queryform' %>
<% end %> 