config/routes.rb
Rails.application.routes.draw do
  resources :potential_buyers
  resources :queries
  resources :properties
  resources :companies
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  # Custom Routes for Users
  match '/user/new', to: 'users#new', via: 'get'
  match '/user/switch', to: 'users#switch', via: 'get', as: 'switch_role_user'
  match '/user/create', to: 'users#create', via: 'post'
  match '/user/:id/edit', to: 'users#edit', via: 'get', as: 'user_edit'
  match '/user/:id', to: 'users#update', via: 'put'
  match '/user/:id', to: 'users#update', via: 'patch'
  match '/user/:id', to: 'users#destroy', via: 'delete'
  match '/users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  # Routes for Property Search
  match '/property/search' => 'properties#search', :via => 'post', :as=> 'property_search'
  # Route to send Enquiry
  match '/property/enquiry' => 'queries#create', :via => 'post', :as => 'new_enquiry'

  # Route to Create New Reply
  match '/queries/reply' => 'queries#reply', :via => :post, :as => :new_reply

  match '/users', to: 'users#index', via: 'get'
  match '/hunters', to: 'users#hunter', via: 'get'
  match '/realtors', to: 'users#realtor', via: 'get'
  root to: "real_estate_app#index"
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_many :properties, dependent: :destroy
  validates_presence_of :name, :address, :website
  validates_length_of :year_founded, is: 4,  message: "Year must be in YYYY"
  enum size: [:"0-50", :"51-200", :"201-500", :"501-1000", :"1000+"]
  enum revenue: [:"Below 1 Million", :"1 to 10 Million", :"10 to 100 Million", :"More than 100 Million"]
  validates :website, url: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    users = User.where(company_id: @company.id)
    users.each do |user|
      user.update({
        company_id: 0
      })
    end
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.fetch(:company, {}).permit(:name, :website, :address, :year_founded, :size, :revenue, :synopsis)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |f| %>
  <div class="container">
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :class => "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :website %>
      <%= f.text_field :website, :class => "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, :class => "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :year_founded %>
      <%= f.text_field :year_founded, :class => "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :size %>
      <%= f.select(:size, Company.sizes.keys, {}, { :class => "form-control" }) %>
    </div>

    <div class="form-group">
      <%= f.label :revenue %>
      <%= f.select(:revenue, Company.revenues.keys, {}, { :class => "form-control"}) %>
    </div>

    <div class="form-group">
      <%= f.label :synopsis %>
      <%= f.text_field :synopsis, :class => "form-control" %>
    </div>

    <% if company.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="form-group">
      <%= f.submit :class=> "btn btn-success" %>
      <%= link_to 'Back', companies_path, :class=>"btn btn-secondary"%>
    </div>
  </div>
<% end %>

app/views/companies/edit.html.erb
<%= render "partials/navbar" %>

<div class="container" style="margin-top:50px">
  <h1>Editing Company</h1>
  <%= render 'form', company: @company %>
</div>

app/views/companies/index.html.erb
<%= render "partials/navbar" %>
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Companies</h1>

  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Website</th>
        <th>Address</th>
        <th>Size</th>
        <th>Revenue</th>
        <th>Synopsis</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @companies.each do |company| %>
        <tr>
          <td><%= company.id %></td>
          <td><%= company.name %></td>
          <td><%= company.website %></td>
          <td><%= company.address %></td>
          <td><%= company.size %></td>
          <td><%= company.revenue %></td>
          <td><%= company.synopsis %></td>

          <% if current_user.is_admin || (current_user.is_realtor && session[:role] == 'realtor' && current_user.company_id == company.id)%>
            <td><%= link_to 'Edit', edit_company_path(company) %></td>
          <%end %>
          <% if current_user.is_admin %>
            <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <% if session[:role] != 'hunter' %>
    <%= link_to 'New Company', new_company_path, :class => "btn btn-success" %>
  <% end %>
</div>

app/views/companies/new.html.erb
<%= render "partials/navbar" %>
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="card" style="width: 36rem; margin-top: 50px;" >
    <div class="card-header">
      Company
    </div>
    <div class="card-body">
      <%= render 'form', company: @company %>
    </div>
  </div>
  </div>
</div>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>