config/routes.rb
Rails.application.routes.draw do
  resources :potential_buyers
  resources :queries
  resources :properties
  resources :companies
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  # Custom Routes for Users
  match '/user/new', to: 'users#new', via: 'get'
  match '/user/switch', to: 'users#switch', via: 'get', as: 'switch_role_user'
  match '/user/create', to: 'users#create', via: 'post'
  match '/user/:id/edit', to: 'users#edit', via: 'get', as: 'user_edit'
  match '/user/:id', to: 'users#update', via: 'put'
  match '/user/:id', to: 'users#update', via: 'patch'
  match '/user/:id', to: 'users#destroy', via: 'delete'
  match '/users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  # Routes for Property Search
  match '/property/search' => 'properties#search', :via => 'post', :as=> 'property_search'
  # Route to send Enquiry
  match '/property/enquiry' => 'queries#create', :via => 'post', :as => 'new_enquiry'

  # Route to Create New Reply
  match '/queries/reply' => 'queries#reply', :via => :post, :as => :new_reply

  match '/users', to: 'users#index', via: 'get'
  match '/hunters', to: 'users#hunter', via: 'get'
  match '/realtors', to: 'users#realtor', via: 'get'
  root to: "real_estate_app#index"
end

app/controllers/real_estate_app_controller.rb
class RealEstateAppController < ApplicationController
  def index
    if !user_signed_in?
      respond_to do |format|
        format.html { redirect_to new_user_session_path }
      end
    end
    if current_user
      if !session[:role].present? && current_user.is_realtor
        session[:role] = 'realtor'
      elsif !session[:role].present? && current_user.is_hunter
        session[:role] = 'hunter'
      end
    end
  end
end

app/helpers/real_estate_app_helper.rb
module RealEstateAppHelper
end

app/views/real_estate_app/index.html.erb
<% provide(:title, "Home") %>
<%= render "partials/navbar" %>
<div class="container" style="margin-top:20px">
  <div class="jumbotron">
    <h1 class="display-4">Hello, <%= current_user.first_name %></h1>
    <p class="lead">Welcome to RealEstate </p>
    <hr class="my-4">
    <div class="list-group">
      <%# All %>

      <%= link_to 'View Properties', properties_path, :class => "list-group-item list-group-item-action"%>
      <%= link_to 'My Enquiries', queries_path, :class => "list-group-item list-group-item-action"%>
      <%= link_to 'View Companies', companies_path, :class=>"list-group-item list-group-item-action"  %>

      <% if session[:role] == 'hunter' %>
        <%= link_to 'My Wishlist', potential_buyers_path, :class=>"list-group-item list-group-item-action"  %>
      <% end %>

      <%# Admin & Realtor %>
      <% if  session[:role] == 'realtor' || current_user.is_admin %>
        <%= link_to 'Add Property', new_property_path, :class=>"list-group-item list-group-item-action"%>
        <%= link_to 'Add Company', new_company_path, :class => "list-group-item list-group-item-action"%>
      <% end %>

      <%# Admin %>
      <% if current_user.is_admin %>
        <%= link_to 'List of Potential Buyers', potential_buyers_path, :method => 'get', :class => "list-group-item list-group-item-action" %>
        <%= link_to 'Add User', { :controller => :users, :action => :new }, :class => "list-group-item list-group-item-action"%>
        <%= link_to 'View Users', users_path, :class=>"list-group-item list-group-item-action"%>
        <%= link_to 'View Hunters', hunters_path, :class => "list-group-item list-group-item-action"%>
        <%= link_to 'View Realtors', realtors_path, :class => "list-group-item list-group-item-action"%>
      <% end %>
    </div>
  </div>
</div>